#ch set-up redux
Abdulkeza/fe-my-portfolio pull request #6
Opened 2022-05-16 21:36 UTC by Abdulkeza

All components are wrapped in provider and is able to access global state

2022-05-16 23:03 UTC, Yvad60 requested changes
Good Job Mr. Abdul with setting Redux, take a look at comments left on some of your files, and also I noticed that your coverage has decreased a lot on this PR you may want to raise it before it got too low
I didn't provide any comments about your redux code as I'm still doing research about it too I will be leaving some comments if any by tomorrow. cheers!

2022-05-16 23:03 UTC, Yvad60 commented on .eslintrc.json
> +		"react/button-has-type": 0,
Why did you disable all these rules

2022-05-16 23:03 UTC, Yvad60 commented on src/redux/actions/index.js
> +// }
if you are not using this file you can safely remove it

2022-05-16 23:03 UTC, Yvad60 commented on package.json
>  		"*.js": "npm run lint",
I don't know the issues with `npm` on my end because I can't install packages. I'm getting an error about the way you used enzyme adapter 16 with react 18
but that may be issue with windows since CI is passing using `ubuntu`

2022-05-16 23:03 UTC, Yvad60 commented on src/tests/App.test.js
> +		expect(wrapper.find('h1').length).toEqual(0);
why are you expecting `expect(wrapper.find('h1').length).toEqual(0)` when there is a  h1 there? shouldn't you expect `1` not `0` ?

2022-05-18 10:53 UTC, Abdulkeza commented on .eslintrc.json
> +		"react/button-has-type": 0,
Also i have to take care of this @yvad, thanks

2022-05-18 10:55 UTC, Abdulkeza commented on package.json
>  		"*.js": "npm run lint",
the issue should be the different OS of enzyme library. I have to fix this also.

2022-05-21 11:00 UTC, Yvad60 approved these changes
Nice work Mr Abudul I noticed that You raised the coverage back to 100% and the counter is working as expected
Approved!

2022-05-21 11:02 UTC, merged